[build-system]
requires = ["setuptools", "dataclasses"]
build-backend = "setuptools.build_meta"

[metadata]
name = checkpointer
version = 0.1.0
description = A simple checkpointing library for Python
author = Jonas Eppelt
author_email = jonas.eppelt@kit.edu
