[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "checkpointer"
version = "0.1.0"
description = "A simple checkpointing library for Python"
license = {text = "MIT License"}
requires-python = ">=3.8"
readme = "README.md"